name: Production Kubernetes Build

on:
  push:
    branches: [ main ]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build_birthday:
      environment: prod 
      runs-on: ubuntu-latest
      env:      
        DOCKER_IMAGE: jiahao19971/birthday

      steps:    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          install: true
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare           
        id: prepare      
        run: |            
          echo ::set-output name=docker_image::${REGISTRY}/${DOCKER_IMAGE}         

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}

      - name: Build birthday image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            NAME=${{ secrets.NAME }} 
            PIC=${{ secrets.PIC }} 
            NICKNAME=${{ secrets.NICKNAME }} 
            SCROLL_MSG=${{ secrets.SCROLL_MSG }} 
            HBD_MSG=${{ secrets.HBD_MSG }}
            OPEN_DATE=${{ secrets.OPEN_DATE }}
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          tags: ${{ steps.prepare.outputs.docker_image }}:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache